import type { Metadata } from "next";
import { Roboto_Serif, Poppins, Chewy } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const chewy = Chewy({
  weight: "400",
  variable: "--font-chewy",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: "500",
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${chewy.variable} ${poppins.variable} antialiased`}>
          <header className="header">Header</header>
          <aside className="sidebar-left">Left Sidebar</aside>
          <main className="main bg-minimal-gridLines">{children}</main>
          <aside className="sidebar-right">Right Sidebar</aside>
          <footer className="footer">Footer</footer>
        </body>
      </html>
    </StoreProvider>
  );
}
